### ISSUE TITLE
 E: Unable to locate package gtk2-engines-adwaita

### ISSUE THREAD

**Issue by shubham7109** [sagarpanchal/arc-theme-ubuntu#2]
lightkun@LightPC:~$ su
Password: 
root@LightPC:/home/lightkun# apt-get install gtk2-engines-pixbuf gtk2-engines-adwaita gnome-themes-standard
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gtk2-engines-adwaita

**Comment by sagarpanchal** [comment]
send me the out put of `lsb_release -a`

**Comment by sagarpanchal** [comment]
![screenshot-github com 2016-05-20 00-00-33](https://cloud.githubusercontent.com/assets/6555461/15405055/f3185422-1e1d-11e6-8b9b-bf2ba3adaf11.png)

You've actually screwed up command.
I see you forked my repo. But, those changes you've done are wrong. The [DOT] " . " at the end of the command denotes current directory to avoid creating a new directory named `arc-theme-ubuntu` in `/usr/share/themes`.

**Comment by sagarpanchal** [comment]
send me the output of `lsb_release -a`

**Comment by sagarpanchal** [comment]
Delete your fork and run following commands.

```
su
rm -rf /usr/share/themes/arc-theme-ubuntu
apt-get install gtk2-engines-pixbuf gtk2-engines-murrine gnome-themes-standard
cd /usr/share/themes/ && rm -rf Arc*
git clone https://github.com/sagarpanchal/arc-theme-ubuntu.git .
rm -rf AUTHORS COPYING README.md screenshots .git && exit
```
